2024-10-30 12:11:58,858 : INFO : Start of Prediction
2024-10-30 12:11:58,858 : INFO : run_id:2024-10-30_121158_575130868
2024-10-30 12:11:58,858 : INFO : Start of Preprocessing...
2024-10-30 12:11:58,858 : INFO : Start of feature encoding...
2024-10-30 12:11:58,861 : INFO : End of feature encoding...
2024-10-30 12:11:58,861 : INFO : Start of Droping Columns...
2024-10-30 12:11:58,862 : INFO : End of Droping Columns...
2024-10-30 12:11:58,863 : INFO : Start of finding missing values...
2024-10-30 12:11:58,865 : INFO : End of finding missing values...
2024-10-30 12:11:58,865 : INFO : Start of building final predictset...
2024-10-30 12:11:58,868 : INFO : End of building final predictset...
2024-10-30 12:11:58,868 : INFO : End of Preprocessing...
2024-10-30 12:11:58,868 : INFO : Start of Load Model
2024-10-30 12:11:58,868 : INFO : Model File KMeans loaded
2024-10-30 12:11:58,868 : INFO : End of Load Model
2024-10-30 12:11:58,869 : ERROR : Unsuccessful End of Prediction
Traceback (most recent call last):
  File "C:\Users\hp\PycharmProjects\EmployeeRetention\apps\prediction\predict_model.py", line 102, in single_predict_from_model
    clusters = kmeans.predict(self.X.drop(['empid'],axis=1))
  File "C:\Users\hp\PycharmProjects\EmployeeRetention\.venv\lib\site-packages\sklearn\cluster\_kmeans.py", line 1058, in predict
    X = self._check_test_data(X)
  File "C:\Users\hp\PycharmProjects\EmployeeRetention\.venv\lib\site-packages\sklearn\cluster\_kmeans.py", line 934, in _check_test_data
    X = self._validate_data(
  File "C:\Users\hp\PycharmProjects\EmployeeRetention\.venv\lib\site-packages\sklearn\base.py", line 548, in _validate_data
    self._check_feature_names(X, reset=reset)
  File "C:\Users\hp\PycharmProjects\EmployeeRetention\.venv\lib\site-packages\sklearn\base.py", line 481, in _check_feature_names
    raise ValueError(message)
ValueError: The feature names should match those that were passed during fit.
Feature names unseen at fit time:
- average_monthly_hours
- work_accident

